services:
  bench:
    image: postgres:10.21
    environment:
      PGPASSWORD: app
    command: pgbench -U app -h publisher -T 60 bench

  publisher:
    build:
      dockerfile: ./Dockerfile
    #image: postgres:10.21
    ports:
      - "5430:5432"
    environment:
      PGUSER: postgres
      PGPASSWORD: password1
      POSTGRES_PASSWORD: password1
    volumes:
      - db-data:/data

  subscriber:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "5431:5432"
    environment:
      PGUSER: postgres
      PGPASSWORD: password2
      POSTGRES_PASSWORD: password2
    volumes:
      - db-data:/data

  subscriber14:
    build:
      dockerfile: ./Dockerfile.pg14
    ports:
      - "5432:5432"
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/data

volumes:
  db-data:
